version: '1'
services:
  scraper_database:
    image: docker.io/library/postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=scraperdatabase
    ports:
      - 5432:5432
    volumes:
      - pgdata_scraper:/var/lib/postgresql/data:Z
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:Z
    networks:
      - scraper_network

  scraper_crawler:
    build:
      context: ./scraper
      dockerfile: Containerfile
    volumes:
      - ./scraper:/app:Z
    depends_on:
      - scraper_database
    networks:
      - scraper_network

networks:
  scraper_network:

volumes:
  pgdata_scraper:
