# python image
FROM python:3.9-slim

# working directory inside the container
WORKDIR /app

# copying files to the working directory
COPY . .

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# setting the entry point for the container
ENTRYPOINT ["python3"]

# running the server
CMD ["server.py"]